version: "3.8"
services:
  dheu-backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./:/app   # optional: mount code for live changes during dev
